# Generated by Django 5.1.2 on 2024-10-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place_name', models.CharField(max_length=250)),
                ('Weather', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=250)),
                ('State', models.CharField(max_length=250)),
                ('District', models.CharField(max_length=250)),
                ('Google_Map_Link', models.CharField(max_length=250)),
                ('Image', models.ImageField(upload_to='Destination/')),
                ('Description', models.CharField(max_length=5000)),
            ],
        ),
    ]
